### ISSUE TITLE
Update lpeglabel in LuaRocks

### ISSUE THREAD

**Issue by andremm** [sqmedeiros/lpeglabel#13]
Please, update lpeglabel in LuaRocks. I got a pull request from @undecidabot that updates lua-parser to use lpeglabel for giving more informative error messages, but it uses its latest version, which is not available in LuaRocks. Many thanks!

**Comment by sqmedeiros** [comment]
I have just updated a new rock:
http://luarocks.org/modules/sergio-medeiros/lpeglabel/1.0.0-1
