### ISSUE TITLE
Please maintain lpeg / re naming...

### ISSUE THREAD

**Issue by snichols** [sqmedeiros/lpeglabel#15]
As someone wanting to drop your system into their own Lua build, it's a small point of friction that I need to change my integration to use lpeglabel / relabel.  Please consider keeping the naming exactly the same as lpeg so you can just drop this in and go.  Thanks!

**Comment by sqmedeiros** [comment]
Hi, Stephen.
I think it would not be fair to keep the name "lpeg". Morever, it would make harder the life of an lpeg user who wants to use lpeglabel in a specific project.
I would suggest you to rename function _luaopen_lpeglabel_ to _luaopen_lpeg_ in **lptree.c**, and then change the makefile according.
