### ISSUE TITLE
Should it be possible to raise an error label from inside a match-time capture?

### ISSUE THREAD

**Issue by hugomg** [sqmedeiros/lpeglabel#19]
In vanilla lpeg, match-time captures (Cmt) can do anything a regular lpeg "subpattern" could. They can match the string at will and figure out the next position of the parser, they can return any captures they want and they can decide to fail the pattern by returning false or nil.

I think it would be very useful if lpeglabel's version of the match time capture were extended to also allow throwing error labels from inside the capture. One possible way to do this would be for the callback function to return `false, errlabel` if it wants to raise an error label.

**Comment by sqmedeiros** [comment]
Hi, @hugomg .

Sorry for the delayed response. It seems a nice feature. I intend to release a new version of LPegLabel until the end of the year, and I will try to incorporate this feature.

I should comment here again when I know whether this feature will be in the next version or not.
