### ISSUE TITLE
A label is not thrown as expected

### ISSUE THREAD

**Issue by ChengCat** [sqmedeiros/lpeglabel#20]
Hi, I am new to lpeglabel, and it seems that I have run into a bug. With the following code, the `Error` label is not thrown as expected, and an ordinary failure is returned instead. Thanks.

```lua
local lpeg = require "lpeglabel"
local P, T = lpeg.P, lpeg.T
local grammar = (P"a" * -P"b" + T"Error") * P"b"
local a, b, c = grammar:match("ab")
print(a, b, c)
```

**Comment by ChengCat** [comment]
I read the paper found [here](https://docs.google.com/viewer?a=v&pid=sites&srcid=ZGVmYXVsdGRvbWFpbnxzcW1lZGVpcm9zfGd4OjMzZmE3YzM0Y2E2MGM5Y2M), and my expectation seems to be correct according to the semantics described in Figure 3.

The issue is caused by [an optimization](https://github.com/sqmedeiros/lpeglabel/blob/3cc98f216871411cdfa1fbc35232d3228126ef91/lpcode.c#L711) in the original lpeg, which doesn't apply to lpeglabel.

**Comment by sqmedeiros** [comment]
Hi. Thanks for the report. Yes, you are right. 'lpeg' has some optimizations that should not be applied when we have labels. An easy fix seems to comment the first part of "||" (headfail(p1)). This can make a bit slower the matching of some patterns. I need to check what would be a fix that does not disable the optmization unnecessarily.

**Comment by ChengCat** [comment]
Sorry, I should have point it out more clearly: by commenting out the `(!e1 && (getfirst(p2, fl, &cs2), cs_disjoint(&cs1, &cs2)))` part (not the `headfail(p1)` part), I can get this issue fixed. I also hope to fix this issue while still retaining maximal performance.

**Comment by sqmedeiros** [comment]
No problem. Try the following change, it should fix the error while still applying the optimization when possible:
https://github.com/sqmedeiros/lpeglabel/commit/88983b5e10e9c46051748349577e84258f7de4a4

**Comment by ChengCat** [comment]
Thank you!
