### ISSUE TITLE
Wrong version returned from version function

### ISSUE THREAD

**Issue by gilzoide** [sqmedeiros/lpeglabel#21]
Calling `lpeglabel.version()` in version 1.5.0 returns `"1.0.1"`

**Comment by sqmedeiros** [comment]
Thanks for the report. This version, 1.0.1, corresponds to the version of LPeg code base used by LPegLabel. 
I think this commit
https://github.com/sqmedeiros/lpeglabel/commit/2e03ab773924ef699a6f5738f6e46cb66da69d9b should fix this issue.

**Comment by gilzoide** [comment]
That solves it, thanks!
I was thinking on querying the library's version, as `relabel.setlabels` function ceased to exist, but ended up setting my code to depend on the lpeglabel rock v1.5 instead. I think it might be good to reflect the lpeglabel version, someone may depend on it (sorry if it was any trouble, as I ended up not needing it).
