### ISSUE TITLE
Is there a way to improve the speed of matching a Name, and make it failed with label when the Name is Reserved?

### ISSUE THREAD

**Issue by sumneko** [sqmedeiros/lpeglabel#22]
Hello, I'm refactoring my parser with Lpeglabel, it worked pretty good.

I've read the documents and most of the related projects, found that people use this way to match the Name:
```
RESERVED    <-  GLOBALS / ENDGLOBALS / CONSTANT / NATIVE / ARRAY / AND / OR / NOT / TYPE / EXTENDS / FUNCTION / ENDFUNCTION / NOTHING / TAKES / RETURNS / CALL / SET / RETURN / IF / ENDIF / ELSEIF / ELSE / LOOP / ENDLOOP / EXITWHEN / TRUE / FALSE
Name        <-  !RESERVED Sp {[a-zA-Z] [a-zA-Z0-9_]*}
```
In may project, the matching speed in this way is about 2.1m/s. (Test with a 6498kb script file)

I tried to change it to this:
```
Name        <-  Sp {[a-zA-Z] [a-zA-Z0-9_]*} -> Reserved
--------------------------------------
function defs.Reserved(name)
    if reserved[name] then
    	error('Reserved name: ' .. name)
    end
    return name
end
```
Then the speed changed to about 3.1m/s. In fact, that's what I did when I used Lpeg: I terminated the match by throwing an error.
But Lpeglabel has provided a more elegant solution, so I don't want to do that anymore.

Then I tried this:
```
Name        <-  Sp {[a-zA-Z] [a-zA-Z0-9_]*} => Reserved
--------------------------------------
function defs.Reserved(_, _, name)
    if reserved[name] then
    	return false
    end
    return true, name
end
```
But Lpeglabel throw an error: too many results in match-time capture.

So is there a way to improve the speed of matching a Name, and make it failed with label when the Name is Reserved?

**Comment by sqmedeiros** [comment]
Hi. Your approach seems ok. I think we could return just **name** in case it is not a reserved word. By doing this maybe we will not reach the limit of match-time captures.

**Comment by sumneko** [comment]
Thank you for your reply. I think I have found a way:
```
Name        <-  Sp {([a-zA-Z] [a-zA-Z0-9_]*) => Reserved}^ERROR_KEY_WORD
----------------------------
function defs.Reserved(_, _, name)
    if reserved[name] then
        return false
    end
    return true
end
```

**Comment by sqmedeiros** [comment]
It is an interesting solution. Did you use a predicate to try to improve the speed more, or to circumvent the error that you reported earlier?

**Comment by sumneko** [comment]
No. I finally gave up on checking the Reserved in the match. Now I check then in next step, see https://github.com/sumneko/JassParser/blob/1be34402c310a2514b0b19a7c0b574a446de3c04/src/parser/init.lua#L41-L45

Consider the following code:
```
globals
    integer a
// should be an 'endglobals' here
function test takes nothing returns nothing
endfunction
```
This is my parser: https://github.com/sumneko/JassParser/blob/1be34402c310a2514b0b19a7c0b574a446de3c04/src/parser/grammarlabel.lua#L316-L337

If I check Reserved in match, it failed so fast then the error will be "Reserved word: 'function'", and my expectations is "Missing 'endglobals'".

**Comment by sqmedeiros** [comment]
Hum, I did not run your code but I think you got "Reserved word: 'function'" because in rule **Global** when trying to match `(GConstant? GType GArray? GName GExp?)`, as `GConstant` is optional, you may have not consumed anything before trying to match `GType`, so you should not thrown a label in case the matching of `GType` fails, because this may just indicate that the matching of `Global*` finished, and the next token is `endglobals`.
On the other hand, when trying to match `GName` you can thrown a label in case this matching fails, because you have already matched something (`GType`), which indicates the matching of this rule should succeed.

**Comment by sumneko** [comment]
Thank you for reading my code and giving me the suggestion!
`GType` is need to check **Reserved** too, and there are many similar places that need extra treatment like this.
In fact I'm very lazy, so I choose to check them in compiling.

Thank you for your patience, I have harvested a lot.

**Comment by sqmedeiros** [comment]
You are welcome :-) 
Good luck with your project.
