### ISSUE TITLE
Clarification in `Functions` section in README

### ISSUE THREAD

**Issue by wqweto** [sqmedeiros/lpeglabel#23]
From `README.md`:

```
#### `p^l`

Syntax of *relabel* module. The pattern `p^l` is equivalent to `p / lpeglabel.T(l)`.
```

Shouldn't the equivalent in `LPegLabel` syntax be stated like `p + lpeglabel.T(l)`?

This is clearly not in `relabel` syntax and I suppose `lpeglabel.T(l)` is in `LPegLabel` syntax because it makes no sense in `relabel` DSL -- it has `%{l}` equivalent of `lpeglabel.T(l)` as far as I understand.

In this case isn't `+` operator for ordered choice while `/` operator is for _apply RHS function to the captures of LHS pattern_?

**Comment by sqmedeiros** [comment]
Yes, you are right. Pattern `p^l` is equivalent to `p + lpeglabel.T(l)`. Thanks for reporting this.
