### ISSUE TITLE
Release new version on luarocks.org

### ISSUE THREAD

**Issue by E-Fir** [sqmedeiros/lpeglabel#33]
Please release new version on [luarocks.org](https://luarocks.org)
https://luarocks.org/modules/sergio-medeiros/lpeglabel
Thank you in advance.

**Comment by sqmedeiros** [comment]
Ok. I expect to release a new version on luarocks next week.

**Comment by agladysh** [comment]
@sqmedeiros Hi! We'd really like to get a release to be able to comply with our internal policy of using only released code. Is there anything we can do to help?

**Comment by sqmedeiros** [comment]
Hi. I'm sorry for the delay. I will start to prepare a new release now. I really think it will be available next week.

**Comment by sqmedeiros** [comment]
Hi. I've just released a new version at github and LuaRocks. Could you please confirm that everything is ok? Merry Christmas :-)

**Comment by Nepta** [comment]
Hi,
unfortunately i got some build error using luajit v2.1:
```sh
In file included from lplcap.c:9:                                                            
lplcap.h:51:10: error: expected ‘;’ before ‘int’            
   51 | LUAI_FUNC int runtimecap (CapState *cs, Capture *close, const char *s, int *rem);
      |          ^~~~                                                                        
      |          ;                                                                           
lplcap.h:52:10: error: expected ‘;’ before ‘int’                                             
   52 | LUAI_FUNC int getcaptures (lua_State *L, const char *s, const char *r, int ptop);    
      |          ^~~~                                                                        
      |          ;                                                                           
lplcap.h:53:10: error: expected ‘;’ before ‘int’                                                                                                                                          
   53 | LUAI_FUNC int finddyncap (Capture *cap, Capture *last);                                                                                                                           
      |          ^~~~                         
      |          ;  
```

doesn't seem too bad tough, LUAI_FUNC shouldn't have existed in lua5.1.
i made it work again by backporting this in _compatibility with 5.1_ section (lpltypes.h)
(but maybe there is a better way to do it ...)
```c
#if defined(__GNUC__) && ((__GNUC__*100 + __GNUC_MINOR__) >= 302) && \
    defined(__ELF__)            /* { */
#define LUAI_FUNC       __attribute__((visibility("hidden"))) extern
#else                           /* }{ */
#define LUAI_FUNC       extern
#endif                          /* } */
```
in any case, merry christmas 🎄

**Comment by sqmedeiros** [comment]
Thanks for the report. I've just looked the source of Lua 5.1 and LUAI_FUNC is there, but it seems it only defined when we are compiling the Lua distribution as a single C source: 
https://www.lua.org/source/5.1/luaconf.h.html

Another option would be to just use a simpler for LUAI_FUNC in case of Lua 5.1.  Maybe the following one would be enough for 5.1:
#ifndef LUAI_FUNC
#define LUAI_FUNC       extern
#endif

Any thoughts about this?

**Comment by Nepta** [comment]
yes, probably the smartest thing to do

**Comment by E-Fir** [comment]
@sqmedeiros Thank you for the release. We really appreciate that.

**Comment by sqmedeiros** [comment]
Hi, @Nepta .

I've just did a commit to deal with the case when LUAI_FUNC was not defined. Could you please confirm that this new version works for you?

**Comment by Nepta** [comment]
it's all good now, thanks

**Comment by Frityet** [comment]
> Hi, @Nepta .
> 
> I've just did a commit to deal with the case when LUAI_FUNC was not defined. Could you please confirm that this new version works for you?

 Could we please get a release with this fix?

**Comment by sqmedeiros** [comment]
Hi, @Frityet . I've just did a new release with this fix. It's also available via luarocks:  https://luarocks.org/modules/sergio-medeiros/lpeglabel

**Comment by Frityet** [comment]
> Hi, @Frityet . I've just did a new release with this fix. It's also available via luarocks: [luarocks.org/modules/sergio-medeiros/lpeglabel](https://luarocks.org/modules/sergio-medeiros/lpeglabel)

Thank you so much!

**Comment by sqmedeiros** [comment]
Closed as a new release as done by the time.
