### ISSUE TITLE
UTF-8 support

### ISSUE THREAD

**Issue by fromsawa** [sqmedeiros/lpeglabel#35]
I just discovered that UTF-8 support is present (is it documented somewhere?) - kudos.

Only, I suggest a minor change to support actual UTF-8 sequences in `utfR`, e.g. 
```.lua
local dashes = U"-" + U"–" + U"—"
local smiley = U"😀"
local any = U"\u{0000}\u{10FFFF}"
```

Attached is a diff I use (note, that I changed the function name from `utfR` to `U` - YMMV):
[lpeglabel-u.zip](https://github.com/sqmedeiros/lpeglabel/files/10489254/lpeglabel-u.zip)

**Comment by sqmedeiros** [comment]
Hi. Actually, this UTF-8 support comes from plain LPeg: http://www.inf.puc-rio.br/~roberto/lpeg/
There is also the irregularly mirrored copy of the LPeg repo: https://github.com/roberto-ieru/LPeg

As you can see, Roberto did a commit related to UTF-8 in 2019, but he did not change the documentation to describe the new `utfR` function.

I would suggest you to talk about these UTF-8 issues (the undocumented `utfR` function and your proposal) on the Lua mailing list: https://www.lua.org/lua-l.html

Thus, Roberto can comment properly about them. 

In case of LPegLabel, for compatibility reasons, I think it is best to change as little as possible from plain LPeg. Usually, when LPeg changes, then LPegLabel changes accordingly. So, let's fist discuss your proposal on the realm of LPeg.

**Comment by fromsawa** [comment]
Thanks a lot for the clarification. 
Will do.
