### ISSUE TITLE
The "relabel" module syntax documentation

### ISSUE THREAD

**Issue by tingtron** [sqmedeiros/lpeglabel#36]
Hello! I like the `relabel` module syntax for being clean and readable.

But apart from reading the sources of `relabel.lua` where can I find documentation for different syntax notations, esp. for the captures like `{ }`, `{: :}`, `{~ ~}`, `{| |}`, etc, and the suffixes `->`, `=>`, `~->` etc?

**Comment by edubart** [comment]
You should look that in LPeg documentation: http://www.inf.puc-rio.br/~roberto/lpeg/re.html

**Comment by tingtron** [comment]
I see. That's what I was looking for. Thank you!
And also they have the PDF with more details there too.
